node:
  ports:
    - "4040:4040"
  image: mroosval/nodemon
  working_dir: /app
  volumes:
    - ./app:/app
  links:
    - mysqld
mysqld:
  image: fenomen/mysqld:latest
  hostname: mysqld
  volumes_from:
    - mysqlddata
  environment:
    - VHOST=fussball
mysqlddata:
  image: fenomen/data:latest
  hostname: mysqlddata
  volumes:
    - /mysqld
  environment:
    - VHOST=fussball
phpmyadmin:
  image: fenomen/phpmyadmin:latest
  hostname: phpmyadmin
  ports:
    - "80"
    - "443"
  links:
    - mysqld
  environment:
    - VHOST=fussbal